/**
 * hsjry.com Inc.
 * Copyright (c) 2015-2020 All Rights Reserved.
 */
package com.david.freedom.plutus.dao;

import com.david.freedom.plutus.entity.RegistrationInfo;
import com.david.freedom.plutus.entity.RegistrationInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * @author hsjry
 * @version $Id: RegistrationInfoMapper.java, v1.0 2020年09月04日 10:47:16 hsjry Exp $
 * @since 1.0
 */
public interface RegistrationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    long countByExample(RegistrationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    int deleteByExample(RegistrationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    int insert(RegistrationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    int insertSelective(RegistrationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    List<RegistrationInfo> selectByExample(RegistrationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    RegistrationInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RegistrationInfo record, @Param("example") RegistrationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RegistrationInfo record, @Param("example") RegistrationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RegistrationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RegistrationInfo record);
}