/**
 * hsjry.com Inc.
 * Copyright (c) 2015-2020 All Rights Reserved.
 */
package com.david.freedom.plutus.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * @author hsjry
 * @version $Id: LoanInvoice.java, v1.0 2020年09月03日 22:07:01 hsjry Exp $
 * @since 1.0
 */
public class LoanInvoice implements Serializable {
    /** 借据id */
    private Long loanInvoiceId;

    /** 借据编号 */
    private String loanInvoiceCode;

    /** 融资申请id */
    private Long financeApplyId;

    /** 融资申请编号 */
    private String financeApplyCode;

    /** 合同id */
    private Long contractId;

    /** 合同编号 */
    private String contractCode;

    /** 融资企业 */
    private String customerId;

    /** 融资企业名称 */
    private String customerName;

    /** 证件类型 */
    private Integer customerIdKind;

    /** 证件号码 */
    private String customerIdNo;

    /** 网络id */
    private Long networkId;

    /** 网络编号 */
    private String networkCode;

    /** 产品名称 */
    private String networkName;

    /** 业务模式 */
    private Integer businessType;

    /** 出账方式(1:流动资金贷款，2：银行承兑汇票) */
    private Integer billingMode;

    /** 产品类型 1-保兑仓 2-采购融资 3-销售订单融资 4-应收账款质押融资 5-国内保理融资 */
    private Integer productType;

    /** 还款方式 1-等额本息，2-等额本金，3：一次性还本付息，4：按频率付息，一次还款 */
    private Integer repayMethod;

    /** 贷款账号 */
    private String loanAccount;

    /** 还款账号 */
    private String repayAccount;

    /** 贷款金额 */
    private BigDecimal loanAmount;

    /** 首付保证金账号 */
    private String marginAccount;

    /** 首付保证金比例 */
    private BigDecimal marginRatio;

    /** 期限方式(0:日,1:月,2:年) */
    private Integer periodType;

    /** 期限（月） */
    private Integer loanPeriod;

    /** 币种(CNY-人民币 HKD-港元 USD-美元) */
    private String currency;

    /** 利率 */
    private BigDecimal interestRate;

    /** 逾期利率 */
    private BigDecimal overdueRate;

    /** 融资开始日期 */
    private Date loanBeginDate;

    /** 融资到期日 */
    private Date loanEndDate;

    /** 剩余未还本金 */
    private BigDecimal leftPrincipal;

    /** 剩余未还利息 */
    private BigDecimal leftInterest;

    /** 剩余未还罚息 */
    private BigDecimal leftPenaltyInterest;

    /** 剩余未还复息 */
    private BigDecimal leftCompoundInterest;

    /** 结息日期 */
    private Date settleDate;

    /** 借据状态（1-正常，2-逾期，3-结清） */
    private Integer loanInvoiceStatus;

    /** 账务机构 */
    private String financeOrganCode;

    /** 业务操作员 */
    private Long userId;

    /** 操作员名称 */
    private String userName;

    /** 操作员机构号 */
    private String organizationCode;

    /** 操作员机构名称 */
    private String organizationName;

    /** 租户号 */
    private String tenantId;

    /** 创建时间 */
    private Date createTime;

    /** 修改时间 */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scm_loan_invoice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.loan_invoice_id
     *
     * @return the value of scm_loan_invoice.loan_invoice_id
     *
     * @mbg.generated
     */
    public Long getLoanInvoiceId() {
        return loanInvoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.loan_invoice_id
     *
     * @param loanInvoiceId the value for scm_loan_invoice.loan_invoice_id
     *
     * @mbg.generated
     */
    public void setLoanInvoiceId(Long loanInvoiceId) {
        this.loanInvoiceId = loanInvoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.loan_invoice_code
     *
     * @return the value of scm_loan_invoice.loan_invoice_code
     *
     * @mbg.generated
     */
    public String getLoanInvoiceCode() {
        return loanInvoiceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.loan_invoice_code
     *
     * @param loanInvoiceCode the value for scm_loan_invoice.loan_invoice_code
     *
     * @mbg.generated
     */
    public void setLoanInvoiceCode(String loanInvoiceCode) {
        this.loanInvoiceCode = loanInvoiceCode == null ? null : loanInvoiceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.finance_apply_id
     *
     * @return the value of scm_loan_invoice.finance_apply_id
     *
     * @mbg.generated
     */
    public Long getFinanceApplyId() {
        return financeApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.finance_apply_id
     *
     * @param financeApplyId the value for scm_loan_invoice.finance_apply_id
     *
     * @mbg.generated
     */
    public void setFinanceApplyId(Long financeApplyId) {
        this.financeApplyId = financeApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.finance_apply_code
     *
     * @return the value of scm_loan_invoice.finance_apply_code
     *
     * @mbg.generated
     */
    public String getFinanceApplyCode() {
        return financeApplyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.finance_apply_code
     *
     * @param financeApplyCode the value for scm_loan_invoice.finance_apply_code
     *
     * @mbg.generated
     */
    public void setFinanceApplyCode(String financeApplyCode) {
        this.financeApplyCode = financeApplyCode == null ? null : financeApplyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.contract_id
     *
     * @return the value of scm_loan_invoice.contract_id
     *
     * @mbg.generated
     */
    public Long getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.contract_id
     *
     * @param contractId the value for scm_loan_invoice.contract_id
     *
     * @mbg.generated
     */
    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.contract_code
     *
     * @return the value of scm_loan_invoice.contract_code
     *
     * @mbg.generated
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.contract_code
     *
     * @param contractCode the value for scm_loan_invoice.contract_code
     *
     * @mbg.generated
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode == null ? null : contractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.customer_id
     *
     * @return the value of scm_loan_invoice.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.customer_id
     *
     * @param customerId the value for scm_loan_invoice.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.customer_name
     *
     * @return the value of scm_loan_invoice.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.customer_name
     *
     * @param customerName the value for scm_loan_invoice.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.customer_id_kind
     *
     * @return the value of scm_loan_invoice.customer_id_kind
     *
     * @mbg.generated
     */
    public Integer getCustomerIdKind() {
        return customerIdKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.customer_id_kind
     *
     * @param customerIdKind the value for scm_loan_invoice.customer_id_kind
     *
     * @mbg.generated
     */
    public void setCustomerIdKind(Integer customerIdKind) {
        this.customerIdKind = customerIdKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.customer_id_no
     *
     * @return the value of scm_loan_invoice.customer_id_no
     *
     * @mbg.generated
     */
    public String getCustomerIdNo() {
        return customerIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.customer_id_no
     *
     * @param customerIdNo the value for scm_loan_invoice.customer_id_no
     *
     * @mbg.generated
     */
    public void setCustomerIdNo(String customerIdNo) {
        this.customerIdNo = customerIdNo == null ? null : customerIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.network_id
     *
     * @return the value of scm_loan_invoice.network_id
     *
     * @mbg.generated
     */
    public Long getNetworkId() {
        return networkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.network_id
     *
     * @param networkId the value for scm_loan_invoice.network_id
     *
     * @mbg.generated
     */
    public void setNetworkId(Long networkId) {
        this.networkId = networkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.network_code
     *
     * @return the value of scm_loan_invoice.network_code
     *
     * @mbg.generated
     */
    public String getNetworkCode() {
        return networkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.network_code
     *
     * @param networkCode the value for scm_loan_invoice.network_code
     *
     * @mbg.generated
     */
    public void setNetworkCode(String networkCode) {
        this.networkCode = networkCode == null ? null : networkCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.network_name
     *
     * @return the value of scm_loan_invoice.network_name
     *
     * @mbg.generated
     */
    public String getNetworkName() {
        return networkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.network_name
     *
     * @param networkName the value for scm_loan_invoice.network_name
     *
     * @mbg.generated
     */
    public void setNetworkName(String networkName) {
        this.networkName = networkName == null ? null : networkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.business_type
     *
     * @return the value of scm_loan_invoice.business_type
     *
     * @mbg.generated
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.business_type
     *
     * @param businessType the value for scm_loan_invoice.business_type
     *
     * @mbg.generated
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.billing_mode
     *
     * @return the value of scm_loan_invoice.billing_mode
     *
     * @mbg.generated
     */
    public Integer getBillingMode() {
        return billingMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.billing_mode
     *
     * @param billingMode the value for scm_loan_invoice.billing_mode
     *
     * @mbg.generated
     */
    public void setBillingMode(Integer billingMode) {
        this.billingMode = billingMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.product_type
     *
     * @return the value of scm_loan_invoice.product_type
     *
     * @mbg.generated
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.product_type
     *
     * @param productType the value for scm_loan_invoice.product_type
     *
     * @mbg.generated
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.repay_method
     *
     * @return the value of scm_loan_invoice.repay_method
     *
     * @mbg.generated
     */
    public Integer getRepayMethod() {
        return repayMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.repay_method
     *
     * @param repayMethod the value for scm_loan_invoice.repay_method
     *
     * @mbg.generated
     */
    public void setRepayMethod(Integer repayMethod) {
        this.repayMethod = repayMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.loan_account
     *
     * @return the value of scm_loan_invoice.loan_account
     *
     * @mbg.generated
     */
    public String getLoanAccount() {
        return loanAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.loan_account
     *
     * @param loanAccount the value for scm_loan_invoice.loan_account
     *
     * @mbg.generated
     */
    public void setLoanAccount(String loanAccount) {
        this.loanAccount = loanAccount == null ? null : loanAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.repay_account
     *
     * @return the value of scm_loan_invoice.repay_account
     *
     * @mbg.generated
     */
    public String getRepayAccount() {
        return repayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.repay_account
     *
     * @param repayAccount the value for scm_loan_invoice.repay_account
     *
     * @mbg.generated
     */
    public void setRepayAccount(String repayAccount) {
        this.repayAccount = repayAccount == null ? null : repayAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.loan_amount
     *
     * @return the value of scm_loan_invoice.loan_amount
     *
     * @mbg.generated
     */
    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.loan_amount
     *
     * @param loanAmount the value for scm_loan_invoice.loan_amount
     *
     * @mbg.generated
     */
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.margin_account
     *
     * @return the value of scm_loan_invoice.margin_account
     *
     * @mbg.generated
     */
    public String getMarginAccount() {
        return marginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.margin_account
     *
     * @param marginAccount the value for scm_loan_invoice.margin_account
     *
     * @mbg.generated
     */
    public void setMarginAccount(String marginAccount) {
        this.marginAccount = marginAccount == null ? null : marginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.margin_ratio
     *
     * @return the value of scm_loan_invoice.margin_ratio
     *
     * @mbg.generated
     */
    public BigDecimal getMarginRatio() {
        return marginRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.margin_ratio
     *
     * @param marginRatio the value for scm_loan_invoice.margin_ratio
     *
     * @mbg.generated
     */
    public void setMarginRatio(BigDecimal marginRatio) {
        this.marginRatio = marginRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.period_type
     *
     * @return the value of scm_loan_invoice.period_type
     *
     * @mbg.generated
     */
    public Integer getPeriodType() {
        return periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.period_type
     *
     * @param periodType the value for scm_loan_invoice.period_type
     *
     * @mbg.generated
     */
    public void setPeriodType(Integer periodType) {
        this.periodType = periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.loan_period
     *
     * @return the value of scm_loan_invoice.loan_period
     *
     * @mbg.generated
     */
    public Integer getLoanPeriod() {
        return loanPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.loan_period
     *
     * @param loanPeriod the value for scm_loan_invoice.loan_period
     *
     * @mbg.generated
     */
    public void setLoanPeriod(Integer loanPeriod) {
        this.loanPeriod = loanPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.currency
     *
     * @return the value of scm_loan_invoice.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.currency
     *
     * @param currency the value for scm_loan_invoice.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.interest_rate
     *
     * @return the value of scm_loan_invoice.interest_rate
     *
     * @mbg.generated
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.interest_rate
     *
     * @param interestRate the value for scm_loan_invoice.interest_rate
     *
     * @mbg.generated
     */
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.overdue_rate
     *
     * @return the value of scm_loan_invoice.overdue_rate
     *
     * @mbg.generated
     */
    public BigDecimal getOverdueRate() {
        return overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.overdue_rate
     *
     * @param overdueRate the value for scm_loan_invoice.overdue_rate
     *
     * @mbg.generated
     */
    public void setOverdueRate(BigDecimal overdueRate) {
        this.overdueRate = overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.loan_begin_date
     *
     * @return the value of scm_loan_invoice.loan_begin_date
     *
     * @mbg.generated
     */
    public Date getLoanBeginDate() {
        return loanBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.loan_begin_date
     *
     * @param loanBeginDate the value for scm_loan_invoice.loan_begin_date
     *
     * @mbg.generated
     */
    public void setLoanBeginDate(Date loanBeginDate) {
        this.loanBeginDate = loanBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.loan_end_date
     *
     * @return the value of scm_loan_invoice.loan_end_date
     *
     * @mbg.generated
     */
    public Date getLoanEndDate() {
        return loanEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.loan_end_date
     *
     * @param loanEndDate the value for scm_loan_invoice.loan_end_date
     *
     * @mbg.generated
     */
    public void setLoanEndDate(Date loanEndDate) {
        this.loanEndDate = loanEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.left_principal
     *
     * @return the value of scm_loan_invoice.left_principal
     *
     * @mbg.generated
     */
    public BigDecimal getLeftPrincipal() {
        return leftPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.left_principal
     *
     * @param leftPrincipal the value for scm_loan_invoice.left_principal
     *
     * @mbg.generated
     */
    public void setLeftPrincipal(BigDecimal leftPrincipal) {
        this.leftPrincipal = leftPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.left_interest
     *
     * @return the value of scm_loan_invoice.left_interest
     *
     * @mbg.generated
     */
    public BigDecimal getLeftInterest() {
        return leftInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.left_interest
     *
     * @param leftInterest the value for scm_loan_invoice.left_interest
     *
     * @mbg.generated
     */
    public void setLeftInterest(BigDecimal leftInterest) {
        this.leftInterest = leftInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.left_penalty_interest
     *
     * @return the value of scm_loan_invoice.left_penalty_interest
     *
     * @mbg.generated
     */
    public BigDecimal getLeftPenaltyInterest() {
        return leftPenaltyInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.left_penalty_interest
     *
     * @param leftPenaltyInterest the value for scm_loan_invoice.left_penalty_interest
     *
     * @mbg.generated
     */
    public void setLeftPenaltyInterest(BigDecimal leftPenaltyInterest) {
        this.leftPenaltyInterest = leftPenaltyInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.left_compound_interest
     *
     * @return the value of scm_loan_invoice.left_compound_interest
     *
     * @mbg.generated
     */
    public BigDecimal getLeftCompoundInterest() {
        return leftCompoundInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.left_compound_interest
     *
     * @param leftCompoundInterest the value for scm_loan_invoice.left_compound_interest
     *
     * @mbg.generated
     */
    public void setLeftCompoundInterest(BigDecimal leftCompoundInterest) {
        this.leftCompoundInterest = leftCompoundInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.settle_date
     *
     * @return the value of scm_loan_invoice.settle_date
     *
     * @mbg.generated
     */
    public Date getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.settle_date
     *
     * @param settleDate the value for scm_loan_invoice.settle_date
     *
     * @mbg.generated
     */
    public void setSettleDate(Date settleDate) {
        this.settleDate = settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.loan_invoice_status
     *
     * @return the value of scm_loan_invoice.loan_invoice_status
     *
     * @mbg.generated
     */
    public Integer getLoanInvoiceStatus() {
        return loanInvoiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.loan_invoice_status
     *
     * @param loanInvoiceStatus the value for scm_loan_invoice.loan_invoice_status
     *
     * @mbg.generated
     */
    public void setLoanInvoiceStatus(Integer loanInvoiceStatus) {
        this.loanInvoiceStatus = loanInvoiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.finance_organ_code
     *
     * @return the value of scm_loan_invoice.finance_organ_code
     *
     * @mbg.generated
     */
    public String getFinanceOrganCode() {
        return financeOrganCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.finance_organ_code
     *
     * @param financeOrganCode the value for scm_loan_invoice.finance_organ_code
     *
     * @mbg.generated
     */
    public void setFinanceOrganCode(String financeOrganCode) {
        this.financeOrganCode = financeOrganCode == null ? null : financeOrganCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.user_id
     *
     * @return the value of scm_loan_invoice.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.user_id
     *
     * @param userId the value for scm_loan_invoice.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.user_name
     *
     * @return the value of scm_loan_invoice.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.user_name
     *
     * @param userName the value for scm_loan_invoice.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.organization_code
     *
     * @return the value of scm_loan_invoice.organization_code
     *
     * @mbg.generated
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.organization_code
     *
     * @param organizationCode the value for scm_loan_invoice.organization_code
     *
     * @mbg.generated
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.organization_name
     *
     * @return the value of scm_loan_invoice.organization_name
     *
     * @mbg.generated
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.organization_name
     *
     * @param organizationName the value for scm_loan_invoice.organization_name
     *
     * @mbg.generated
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName == null ? null : organizationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.tenant_id
     *
     * @return the value of scm_loan_invoice.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.tenant_id
     *
     * @param tenantId the value for scm_loan_invoice.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.create_time
     *
     * @return the value of scm_loan_invoice.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.create_time
     *
     * @param createTime the value for scm_loan_invoice.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm_loan_invoice.update_time
     *
     * @return the value of scm_loan_invoice.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm_loan_invoice.update_time
     *
     * @param updateTime the value for scm_loan_invoice.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm_loan_invoice
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LoanInvoice other = (LoanInvoice) that;
        return (this.getLoanInvoiceId() == null ? other.getLoanInvoiceId() == null : this.getLoanInvoiceId().equals(other.getLoanInvoiceId()))
            && (this.getLoanInvoiceCode() == null ? other.getLoanInvoiceCode() == null : this.getLoanInvoiceCode().equals(other.getLoanInvoiceCode()))
            && (this.getFinanceApplyId() == null ? other.getFinanceApplyId() == null : this.getFinanceApplyId().equals(other.getFinanceApplyId()))
            && (this.getFinanceApplyCode() == null ? other.getFinanceApplyCode() == null : this.getFinanceApplyCode().equals(other.getFinanceApplyCode()))
            && (this.getContractId() == null ? other.getContractId() == null : this.getContractId().equals(other.getContractId()))
            && (this.getContractCode() == null ? other.getContractCode() == null : this.getContractCode().equals(other.getContractCode()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getCustomerName() == null ? other.getCustomerName() == null : this.getCustomerName().equals(other.getCustomerName()))
            && (this.getCustomerIdKind() == null ? other.getCustomerIdKind() == null : this.getCustomerIdKind().equals(other.getCustomerIdKind()))
            && (this.getCustomerIdNo() == null ? other.getCustomerIdNo() == null : this.getCustomerIdNo().equals(other.getCustomerIdNo()))
            && (this.getNetworkId() == null ? other.getNetworkId() == null : this.getNetworkId().equals(other.getNetworkId()))
            && (this.getNetworkCode() == null ? other.getNetworkCode() == null : this.getNetworkCode().equals(other.getNetworkCode()))
            && (this.getNetworkName() == null ? other.getNetworkName() == null : this.getNetworkName().equals(other.getNetworkName()))
            && (this.getBusinessType() == null ? other.getBusinessType() == null : this.getBusinessType().equals(other.getBusinessType()))
            && (this.getBillingMode() == null ? other.getBillingMode() == null : this.getBillingMode().equals(other.getBillingMode()))
            && (this.getProductType() == null ? other.getProductType() == null : this.getProductType().equals(other.getProductType()))
            && (this.getRepayMethod() == null ? other.getRepayMethod() == null : this.getRepayMethod().equals(other.getRepayMethod()))
            && (this.getLoanAccount() == null ? other.getLoanAccount() == null : this.getLoanAccount().equals(other.getLoanAccount()))
            && (this.getRepayAccount() == null ? other.getRepayAccount() == null : this.getRepayAccount().equals(other.getRepayAccount()))
            && (this.getLoanAmount() == null ? other.getLoanAmount() == null : this.getLoanAmount().equals(other.getLoanAmount()))
            && (this.getMarginAccount() == null ? other.getMarginAccount() == null : this.getMarginAccount().equals(other.getMarginAccount()))
            && (this.getMarginRatio() == null ? other.getMarginRatio() == null : this.getMarginRatio().equals(other.getMarginRatio()))
            && (this.getPeriodType() == null ? other.getPeriodType() == null : this.getPeriodType().equals(other.getPeriodType()))
            && (this.getLoanPeriod() == null ? other.getLoanPeriod() == null : this.getLoanPeriod().equals(other.getLoanPeriod()))
            && (this.getCurrency() == null ? other.getCurrency() == null : this.getCurrency().equals(other.getCurrency()))
            && (this.getInterestRate() == null ? other.getInterestRate() == null : this.getInterestRate().equals(other.getInterestRate()))
            && (this.getOverdueRate() == null ? other.getOverdueRate() == null : this.getOverdueRate().equals(other.getOverdueRate()))
            && (this.getLoanBeginDate() == null ? other.getLoanBeginDate() == null : this.getLoanBeginDate().equals(other.getLoanBeginDate()))
            && (this.getLoanEndDate() == null ? other.getLoanEndDate() == null : this.getLoanEndDate().equals(other.getLoanEndDate()))
            && (this.getLeftPrincipal() == null ? other.getLeftPrincipal() == null : this.getLeftPrincipal().equals(other.getLeftPrincipal()))
            && (this.getLeftInterest() == null ? other.getLeftInterest() == null : this.getLeftInterest().equals(other.getLeftInterest()))
            && (this.getLeftPenaltyInterest() == null ? other.getLeftPenaltyInterest() == null : this.getLeftPenaltyInterest().equals(other.getLeftPenaltyInterest()))
            && (this.getLeftCompoundInterest() == null ? other.getLeftCompoundInterest() == null : this.getLeftCompoundInterest().equals(other.getLeftCompoundInterest()))
            && (this.getSettleDate() == null ? other.getSettleDate() == null : this.getSettleDate().equals(other.getSettleDate()))
            && (this.getLoanInvoiceStatus() == null ? other.getLoanInvoiceStatus() == null : this.getLoanInvoiceStatus().equals(other.getLoanInvoiceStatus()))
            && (this.getFinanceOrganCode() == null ? other.getFinanceOrganCode() == null : this.getFinanceOrganCode().equals(other.getFinanceOrganCode()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getOrganizationCode() == null ? other.getOrganizationCode() == null : this.getOrganizationCode().equals(other.getOrganizationCode()))
            && (this.getOrganizationName() == null ? other.getOrganizationName() == null : this.getOrganizationName().equals(other.getOrganizationName()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm_loan_invoice
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLoanInvoiceId() == null) ? 0 : getLoanInvoiceId().hashCode());
        result = prime * result + ((getLoanInvoiceCode() == null) ? 0 : getLoanInvoiceCode().hashCode());
        result = prime * result + ((getFinanceApplyId() == null) ? 0 : getFinanceApplyId().hashCode());
        result = prime * result + ((getFinanceApplyCode() == null) ? 0 : getFinanceApplyCode().hashCode());
        result = prime * result + ((getContractId() == null) ? 0 : getContractId().hashCode());
        result = prime * result + ((getContractCode() == null) ? 0 : getContractCode().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getCustomerName() == null) ? 0 : getCustomerName().hashCode());
        result = prime * result + ((getCustomerIdKind() == null) ? 0 : getCustomerIdKind().hashCode());
        result = prime * result + ((getCustomerIdNo() == null) ? 0 : getCustomerIdNo().hashCode());
        result = prime * result + ((getNetworkId() == null) ? 0 : getNetworkId().hashCode());
        result = prime * result + ((getNetworkCode() == null) ? 0 : getNetworkCode().hashCode());
        result = prime * result + ((getNetworkName() == null) ? 0 : getNetworkName().hashCode());
        result = prime * result + ((getBusinessType() == null) ? 0 : getBusinessType().hashCode());
        result = prime * result + ((getBillingMode() == null) ? 0 : getBillingMode().hashCode());
        result = prime * result + ((getProductType() == null) ? 0 : getProductType().hashCode());
        result = prime * result + ((getRepayMethod() == null) ? 0 : getRepayMethod().hashCode());
        result = prime * result + ((getLoanAccount() == null) ? 0 : getLoanAccount().hashCode());
        result = prime * result + ((getRepayAccount() == null) ? 0 : getRepayAccount().hashCode());
        result = prime * result + ((getLoanAmount() == null) ? 0 : getLoanAmount().hashCode());
        result = prime * result + ((getMarginAccount() == null) ? 0 : getMarginAccount().hashCode());
        result = prime * result + ((getMarginRatio() == null) ? 0 : getMarginRatio().hashCode());
        result = prime * result + ((getPeriodType() == null) ? 0 : getPeriodType().hashCode());
        result = prime * result + ((getLoanPeriod() == null) ? 0 : getLoanPeriod().hashCode());
        result = prime * result + ((getCurrency() == null) ? 0 : getCurrency().hashCode());
        result = prime * result + ((getInterestRate() == null) ? 0 : getInterestRate().hashCode());
        result = prime * result + ((getOverdueRate() == null) ? 0 : getOverdueRate().hashCode());
        result = prime * result + ((getLoanBeginDate() == null) ? 0 : getLoanBeginDate().hashCode());
        result = prime * result + ((getLoanEndDate() == null) ? 0 : getLoanEndDate().hashCode());
        result = prime * result + ((getLeftPrincipal() == null) ? 0 : getLeftPrincipal().hashCode());
        result = prime * result + ((getLeftInterest() == null) ? 0 : getLeftInterest().hashCode());
        result = prime * result + ((getLeftPenaltyInterest() == null) ? 0 : getLeftPenaltyInterest().hashCode());
        result = prime * result + ((getLeftCompoundInterest() == null) ? 0 : getLeftCompoundInterest().hashCode());
        result = prime * result + ((getSettleDate() == null) ? 0 : getSettleDate().hashCode());
        result = prime * result + ((getLoanInvoiceStatus() == null) ? 0 : getLoanInvoiceStatus().hashCode());
        result = prime * result + ((getFinanceOrganCode() == null) ? 0 : getFinanceOrganCode().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getOrganizationCode() == null) ? 0 : getOrganizationCode().hashCode());
        result = prime * result + ((getOrganizationName() == null) ? 0 : getOrganizationName().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm_loan_invoice
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", loanInvoiceId=").append(loanInvoiceId);
        sb.append(", loanInvoiceCode=").append(loanInvoiceCode);
        sb.append(", financeApplyId=").append(financeApplyId);
        sb.append(", financeApplyCode=").append(financeApplyCode);
        sb.append(", contractId=").append(contractId);
        sb.append(", contractCode=").append(contractCode);
        sb.append(", customerId=").append(customerId);
        sb.append(", customerName=").append(customerName);
        sb.append(", customerIdKind=").append(customerIdKind);
        sb.append(", customerIdNo=").append(customerIdNo);
        sb.append(", networkId=").append(networkId);
        sb.append(", networkCode=").append(networkCode);
        sb.append(", networkName=").append(networkName);
        sb.append(", businessType=").append(businessType);
        sb.append(", billingMode=").append(billingMode);
        sb.append(", productType=").append(productType);
        sb.append(", repayMethod=").append(repayMethod);
        sb.append(", loanAccount=").append(loanAccount);
        sb.append(", repayAccount=").append(repayAccount);
        sb.append(", loanAmount=").append(loanAmount);
        sb.append(", marginAccount=").append(marginAccount);
        sb.append(", marginRatio=").append(marginRatio);
        sb.append(", periodType=").append(periodType);
        sb.append(", loanPeriod=").append(loanPeriod);
        sb.append(", currency=").append(currency);
        sb.append(", interestRate=").append(interestRate);
        sb.append(", overdueRate=").append(overdueRate);
        sb.append(", loanBeginDate=").append(loanBeginDate);
        sb.append(", loanEndDate=").append(loanEndDate);
        sb.append(", leftPrincipal=").append(leftPrincipal);
        sb.append(", leftInterest=").append(leftInterest);
        sb.append(", leftPenaltyInterest=").append(leftPenaltyInterest);
        sb.append(", leftCompoundInterest=").append(leftCompoundInterest);
        sb.append(", settleDate=").append(settleDate);
        sb.append(", loanInvoiceStatus=").append(loanInvoiceStatus);
        sb.append(", financeOrganCode=").append(financeOrganCode);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", organizationCode=").append(organizationCode);
        sb.append(", organizationName=").append(organizationName);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}